### ISSUE TITLE
Be able to see the difference between invisible mobs and non invisible mobs?

### ISSUE THREAD

**Issue by mcgamerguy** [Roundaround/mc-fabric-true-sight#6]
I was wondering if you could add a setting using mod menu or a / command where you could toggle only being able to see invisible entities partially, like 50% opacity

**Comment by Roundaround** [comment]
As much as I'd like to say yes, the way this mod works is that the game checks whether a mob is invisible and if so just skips rendering it entirely, and this mod basically hijacks and overrides that invisibility check when you have the option enabled. I don't actually touch rendering code, and for the purposes of mod compatibility and maintenance I'm not currently interested in adding it. Sorry!
